--[[
	--- This is Wilson's speech file for Don't Starve Together ---
	Write your character's lines here. If you want to use another speech file as a base, get them from data\scripts\
	
	If you have the DLC and want custom lines for those, use a speech file from data\DLC0001\scripts instead.
	
	If you want to use quotation marks in a quote, put a \ before it.
	Example:
	"Like \"this\"."
]]
return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			NOBITS = "Gao! Gao! Gao!",
		},
		STORE =
		{
			GENERIC = "Gao! Gao! Gao!",
			NOTALLOWED = "Gao! Gao! Gao!",
			INUSE = "Gao! Gao! Gao!",
		},
		RUMMAGE =
		{	
			GENERIC = "Gao! Gao! Gao!",
			INUSE = "Gao! Gao! Gao!",	
		},
	},
	ACTIONFAIL_GENERIC = "Gao! Gao! Gao!",
	ANNOUNCE_ADVENTUREFAIL = "Gao! Gao! Gao!",
	ANNOUNCE_BEES = "Gao! Gao! Gao!",
	ANNOUNCE_BOOMERANG = "Gao! Gao! Gao!",
	ANNOUNCE_CHARLIE = "Gao! Gao! Gao!",
	ANNOUNCE_CHARLIE_ATTACK = "Gao! Gao! Gao!",
	ANNOUNCE_COLD = "Gao! Gao! Gao!",
	ANNOUNCE_CRAFTING_FAIL = "Gao! Gao! Gao!",
	ANNOUNCE_DEERCLOPS = "Gao! Gao! Gao!",
	ANNOUNCE_DUSK = "Gao! Gao! Gao!",
	ANNOUNCE_EAT =
	{
		GENERIC = "Gao! Gao! Gao!",
		PAINFUL = "Gao! Gao! Gao!",
		SPOILED = "Gao! Gao! Gao!",
		STALE = "Gao! Gao! Gao!",
	},
	ANNOUNCE_ENTER_DARK = "Gao! Gao! Gao!",
	ANNOUNCE_ENTER_LIGHT = "Gao! Gao! Gao!",
	ANNOUNCE_FREEDOM = "Gao! Gao! Gao!",
	ANNOUNCE_HIGHRESEARCH = "Gao! Gao! Gao!",
	ANNOUNCE_HOUNDS = "Gao! Gao! Gao!",
	ANNOUNCE_HUNGRY = "Gao! Gao! Gao!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Gao! Gao! Gao!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Gao! Gao! Gao!",
	ANNOUNCE_INV_FULL = "Gao! Gao! Gao!",
	ANNOUNCE_KNOCKEDOUT = "Gao! Gao! Gao!",
	ANNOUNCE_LOWRESEARCH = "Gao! Gao! Gao!",
	ANNOUNCE_MOSQUITOS = "Gao! Gao! Gao!",
	ANNOUNCE_NODANGERSLEEP = "Gao! Gao! Gao!",
	ANNOUNCE_NODAYSLEEP = "Gao! Gao! Gao!",
	ANNOUNCE_NODAYSLEEP_CAVE = "Gao! Gao! Gao!",
	ANNOUNCE_NOHUNGERSLEEP = "Gao! Gao! Gao!",
	ANNOUNCE_NODANGERAFK = "Gao! Gao! Gao!",
	ANNOUNCE_NO_TRAP = "Gao! Gao! Gao!",
	ANNOUNCE_PECKED = "Gao! Gao! Gao!",
	ANNOUNCE_QUAKE = "Gao! Gao! Gao!",
	ANNOUNCE_RESEARCH = "Gao! Gao! Gao!",
	ANNOUNCE_THORNS = "Gao! Gao! Gao!",
	ANNOUNCE_TORCH_OUT = "Gao! Gao! Gao!",
	ANNOUNCE_TRAP_WENT_OFF = "Gao! Gao! Gao!",
	ANNOUNCE_UNIMPLEMENTED = "Gao! Gao! Gao!",
	ANNOUNCE_WORMHOLE = "Gao! Gao! Gao!",
	ANNOUNCE_CANFIX = "\nGao! Gao! Gao!",
	ANNOUNCE_ACCOMPLISHMENT = "Gao! Gao! Gao!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Gao! Gao! Gao!",	
	ANNOUNCE_BECOMEGHOST = "Gao! Gao! Gao!",
	ANNOUNCE_GHOSTDRAIN = "Gao! Gao! Gao!",

	DESCRIBE_SAMECHARACTER = "Gao! Gao! Gao!",
	
	BATTLECRY =
	{
		GENERIC = "Gao! Gao! Gao!",
		PIG = "Gao! Gao! Gao!",
		PREY = "Gao! Gao! Gao!",
		SPIDER = "Gao! Gao! Gao!",
		SPIDER_WARRIOR = "Gao! Gao! Gao!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Gao! Gao! Gao!",
		PIG = "Gao! Gao! Gao!",
		PREY = "Gao! Gao! Gao!",
		SPIDER = "Gao! Gao! Gao!",
		SPIDER_WARRIOR = "Gao! Gao! Gao!",
	},
	DESCRIBE =
	{
        PLAYER =
        {
            GENERIC = "Gao! Gao! Gao!",
            ATTACKER = "Gao! Gao! Gao!",
            MURDERER = "Gao! Gao! Gao!",
            REVIVER = "Gao! Gao! Gao!",
            GHOST = "Gao! Gao! Gao!",
        },
		WILSON = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WOLFGANG = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WAXWELL = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WX78 = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WILLOW = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WENDY = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WOODIE = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		WES = 
		{
			GENERIC = "Gao! Gao! Gao!",
			ATTACKER = "Gao! Gao! Gao!",
			MURDERER = "Gao! Gao! Gao!",
			REVIVER = "Gao! Gao! Gao!",
			GHOST = "Gao! Gao! Gao!",
		},
		MULTIPLAYER_PORTAL = "Gao! Gao! Gao!",
		WORMLIGHT = "Gao! Gao! Gao!",
		WORM =
		{
		    PLANT = "Gao! Gao! Gao!",
		    DIRT = "Gao! Gao! Gao!",
		    WORM = "Gao! Gao! Gao!",
		},
		MOLE =
		{
			HELD = "Gao! Gao! Gao!",
			UNDERGROUND = "Gao! Gao! Gao!",
			ABOVEGROUND = "Gao! Gao! Gao!",
		},
		MOLEHILL = "Gao! Gao! Gao!",
		MOLEHAT = "Gao! Gao! Gao!",

		EEL = "Gao! Gao! Gao!",
		EEL_COOKED = "Gao! Gao! Gao!",
		UNAGI = "Gao! Gao! Gao!",
		EYETURRET = "Gao! Gao! Gao!",
		EYETURRET_ITEM = "Gao! Gao! Gao!",
		MINOTAURHORN = "Gao! Gao! Gao!",
		MINOTAURCHEST = "Gao! Gao! Gao!",
		THULECITE_PIECES = "Gao! Gao! Gao!",
		POND_ALGAE = "Gao! Gao! Gao!",
		GREENSTAFF = "Gao! Gao! Gao!",
		POTTEDFERN = "Gao! Gao! Gao!",

		THULECITE = "Gao! Gao! Gao!",
		ARMORRUINS = "Gao! Gao! Gao!",
		RUINS_BAT = "Gao! Gao! Gao!",
		RUINSHAT = "Gao! Gao! Gao!",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "Gao! Gao! Gao!",
		WARN = "Gao! Gao! Gao!",
		WAXING = "Gao! Gao! Gao!",
		STEADY = "Gao! Gao! Gao!",
		WANING = "Gao! Gao! Gao!",
		DAWN = "Gao! Gao! Gao!",
		NOMAGIC = "Gao! Gao! Gao!",
		},
		BISHOP_NIGHTMARE = "Gao! Gao! Gao!",
		ROOK_NIGHTMARE = "Gao! Gao! Gao!",
		KNIGHT_NIGHTMARE = "Gao! Gao! Gao!",
		MINOTAUR = "Gao! Gao! Gao!",
		SPIDER_DROPPER = "Gao! Gao! Gao!",
		NIGHTMARELIGHT = "Gao! Gao! Gao!",
		GREENGEM = "Gao! Gao! Gao!",
		RELIC = "Gao! Gao! Gao!",
		RUINS_RUBBLE = "Gao! Gao! Gao!",
		MULTITOOL_AXE_PICKAXE = "Gao! Gao! Gao!",
		ORANGESTAFF = "Gao! Gao! Gao!",
		YELLOWAMULET = "Gao! Gao! Gao!",
		GREENAMULET = "Gao! Gao! Gao!",
		SLURPERPELT = "Gao! Gao! Gao!",	

		SLURPER = "Gao! Gao! Gao!",
		SLURPER_PELT = "Gao! Gao! Gao!",
		ARMORSLURPER = "Gao! Gao! Gao!",
		ORANGEAMULET = "Gao! Gao! Gao!",
		YELLOWSTAFF = "Gao! Gao! Gao!",
		YELLOWGEM = "Gao! Gao! Gao!",
		ORANGEGEM = "Gao! Gao! Gao!",
		TELEBASE = 
		{
			VALID = "Gao! Gao! Gao!",
			GEMS = "Gao! Gao! Gao!",
		},
		GEMSOCKET = 
		{
			VALID = "Gao! Gao! Gao!",
			GEMS = "Gao! Gao! Gao!",
		},
		STAFFLIGHT = "Gao! Gao! Gao!",
		RESEARCHLAB4 = "Gao! Gao! Gao!",
	
        ANCIENT_ALTAR = "Gao! Gao! Gao!",

        ANCIENT_ALTAR_BROKEN = "Gao! Gao! Gao!",

        ANCIENT_STATUE = "Gao! Gao! Gao!",

        LICHEN = "Gao! Gao! Gao!",
		CUTLICHEN = "Gao! Gao! Gao!",

		CAVE_BANANA = "Gao! Gao! Gao!",
		CAVE_BANANA_COOKED = "Gao! Gao! Gao!",
		CAVE_BANANA_TREE = "Gao! Gao! Gao!",
		ROCKY = "Gao! Gao! Gao!",
		
		COMPASS =
		{
			GENERIC="Gao! Gao! Gao!",
			N = "Gao! Gao! Gao!",
			S = "Gao! Gao! Gao!",
			E = "Gao! Gao! Gao!",
			W = "Gao! Gao! Gao!",
			NE = "Gao! Gao! Gao!",
			SE = "Gao! Gao! Gao!",
			NW = "Gao! Gao! Gao!",
			SW = "Gao! Gao! Gao!",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "Gao! Gao! Gao!",
			STEADY = "Gao! Gao! Gao!",
			WANING = "Gao! Gao! Gao!",
			DAWN = "Gao! Gao! Gao!",
			WARN = "Gao! Gao! Gao!",
			CALM = "Gao! Gao! Gao!",
			NOMAGIC = "Gao! Gao! Gao!",
		},

		HOUNDSTOOTH="Gao! Gao! Gao!",
		ARMORSNURTLESHELL="Gao! Gao! Gao!",
		BAT="Gao! Gao! Gao!",
		BATBAT = "Gao! Gao! Gao!",
		BATWING="Gao! Gao! Gao!",
		BATWING_COOKED="Gao! Gao! Gao!",
		BEDROLL_FURRY="Gao! Gao! Gao!",
		BUNNYMAN="Gao! Gao! Gao!",
		FLOWER_CAVE="Gao! Gao! Gao!",
		FLOWER_CAVE_DOUBLE="Gao! Gao! Gao!",
		FLOWER_CAVE_TRIPLE="Gao! Gao! Gao!",
		GUANO="Gao! Gao! Gao!",
		LANTERN="Gao! Gao! Gao!",
		LIGHTBULB="Gao! Gao! Gao!",
		MANRABBIT_TAIL="Gao! Gao! Gao!",
		MUSHTREE_TALL  ="Gao! Gao! Gao!",
		MUSHTREE_MEDIUM="Gao! Gao! Gao!",
		MUSHTREE_SMALL ="Gao! Gao! Gao!",
		RABBITHOUSE="Gao! Gao! Gao!",
		SLURTLE="Gao! Gao! Gao!",
		SLURTLE_SHELLPIECES="Gao! Gao! Gao!",
		SLURTLEHAT="Gao! Gao! Gao!",
		SLURTLEHOLE="Gao! Gao! Gao!",
		SLURTLESLIME="Gao! Gao! Gao!",
		SNURTLE="Gao! Gao! Gao!",
		SPIDER_HIDER="Gao! Gao! Gao!",
		SPIDER_SPITTER="Gao! Gao! Gao!",
		SPIDERHOLE="Gao! Gao! Gao!",
		STALAGMITE="Gao! Gao! Gao!",
		STALAGMITE_FULL="Gao! Gao! Gao!",
		STALAGMITE_LOW="Gao! Gao! Gao!",
		STALAGMITE_MED="Gao! Gao! Gao!",
		STALAGMITE_TALL="Gao! Gao! Gao!",
		STALAGMITE_TALL_FULL="Gao! Gao! Gao!",
		STALAGMITE_TALL_LOW="Gao! Gao! Gao!",
		STALAGMITE_TALL_MED="Gao! Gao! Gao!",

		TURF_CARPETFLOOR = "Gao! Gao! Gao!",
		TURF_CHECKERFLOOR = "Gao! Gao! Gao!",
		TURF_DIRT = "Gao! Gao! Gao!",
		TURF_FOREST = "Gao! Gao! Gao!",
		TURF_GRASS = "Gao! Gao! Gao!",
		TURF_MARSH = "Gao! Gao! Gao!",
		TURF_ROAD = "Gao! Gao! Gao!",
		TURF_ROCKY = "Gao! Gao! Gao!",
		TURF_SAVANNA = "Gao! Gao! Gao!",
		TURF_WOODFLOOR = "Gao! Gao! Gao!",

		TURF_CAVE="Gao! Gao! Gao!",
		TURF_FUNGUS="Gao! Gao! Gao!",
		TURF_SINKHOLE="Gao! Gao! Gao!",
		TURF_UNDERROCK="Gao! Gao! Gao!",
		TURF_MUD="Gao! Gao! Gao!",

		POWCAKE = "Gao! Gao! Gao!",
        CAVE_ENTRANCE = 
        {
            GENERIC="Gao! Gao! Gao!",
            OPEN = "Gao! Gao! Gao!",
        },
        CAVE_EXIT = "Gao! Gao! Gao!",
		MAXWELLPHONOGRAPH = "Gao! Gao! Gao!",
		BOOMERANG = "Gao! Gao! Gao!",
		PIGGUARD = "Gao! Gao! Gao!",
		ABIGAIL = "Gao! Gao! Gao!",
		ADVENTURE_PORTAL = "Gao! Gao! Gao!",
		AMULET = "Gao! Gao! Gao!",
		ANIMAL_TRACK = "Gao! Gao! Gao!",
		ARMORGRASS = "Gao! Gao! Gao!",
		ARMORMARBLE = "Gao! Gao! Gao!",
		ARMORWOOD = "Gao! Gao! Gao!",
		ARMOR_SANITY = "Gao! Gao! Gao!",
		ASH =
		{
			GENERIC = "Gao! Gao! Gao!",
			REMAINS_EYE_BONE = "Gao! Gao! Gao!",
			REMAINS_THINGIE = "Gao! Gao! Gao!",
		},
		AXE = "Gao! Gao! Gao!",
		BABYBEEFALO = "Gao! Gao! Gao!",
		BACKPACK = "Gao! Gao! Gao!",
		BACONEGGS = "Gao! Gao! Gao!",
		BANDAGE = "Gao! Gao! Gao!",
		BASALT = "Gao! Gao! Gao!",
		BATBAT = "Gao! Gao! Gao!",
		BEARDHAIR = "Gao! Gao! Gao!",
		BEDROLL_STRAW = "Gao! Gao! Gao!",
		BEE =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		BEEBOX =
		{
			FULLHONEY = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			NOHONEY = "Gao! Gao! Gao!",
			SOMEHONEY = "Gao! Gao! Gao!",
		},
		BEEFALO =
		{
			FOLLOWER = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			NAKED = "Gao! Gao! Gao!",
			SLEEPING = "Gao! Gao! Gao!",
		},
		BEEFALOHAT = "Gao! Gao! Gao!",
		BEEFALOWOOL = "Gao! Gao! Gao!",
		BEEHAT = "Gao! Gao! Gao!",
		BEEHIVE = "Gao! Gao! Gao!",
		BEEMINE = "Gao! Gao! Gao!",
		BEEMINE_MAXWELL = "Gao! Gao! Gao!",
		BERRIES = "Gao! Gao! Gao!",
		BERRIES_COOKED = "Gao! Gao! Gao!",
		BERRYBUSH =
		{
			BARREN = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		BIRDCAGE =
		{
			GENERIC = "Gao! Gao! Gao!",
			OCCUPIED = "Gao! Gao! Gao!",
			SLEEPING = "Gao! Gao! Gao!",
		},
		BIRDTRAP = "Gao! Gao! Gao!",
		BIRD_EGG = "Gao! Gao! Gao!",
		BIRD_EGG_COOKED = "Gao! Gao! Gao!",
		BISHOP = "Gao! Gao! Gao!",
		BLOWDART_FIRE = "Gao! Gao! Gao!",
		BLOWDART_SLEEP = "Gao! Gao! Gao!",
		BLOWDART_PIPE = "Gao! Gao! Gao!",
		BLUEAMULET = "Gao! Gao! Gao!",
		BLUEGEM = "Gao! Gao! Gao!",
		BLUEPRINT = "Gao! Gao! Gao!",
		BLUE_CAP = "Gao! Gao! Gao!",
		BLUE_CAP_COOKED = "Gao! Gao! Gao!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Gao! Gao! Gao!",
			INGROUND = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		BOARDS = "Gao! Gao! Gao!",
		BOAT = "Gao! Gao! Gao!",
		BONESTEW = "Gao! Gao! Gao!",
		BUGNET = "Gao! Gao! Gao!",
		BUSHHAT = "Gao! Gao! Gao!",
		BUTTER = "Gao! Gao! Gao!",
		BUTTERFLY =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		BUTTERFLYMUFFIN = "Gao! Gao! Gao!",
		BUTTERFLYWINGS = "Gao! Gao! Gao!",
		CAMPFIRE =
		{
			EMBERS = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			HIGH = "Gao! Gao! Gao!",
			LOW = "Gao! Gao! Gao!",
			NORMAL = "Gao! Gao! Gao!",
			OUT = "Gao! Gao! Gao!",
		},
		CANE = "Gao! Gao! Gao!",
		CARROT = "Gao! Gao! Gao!",
		CARROT_COOKED = "Gao! Gao! Gao!",
		CARROT_PLANTED = "Gao! Gao! Gao!",
		CARROT_SEEDS = "Gao! Gao! Gao!",
		CAVE_FERN = "Gao! Gao! Gao!",
		CHARCOAL = "Gao! Gao! Gao!",
        CHESSJUNK1 = "Gao! Gao! Gao!",
        CHESSJUNK2 = "Gao! Gao! Gao!",
        CHESSJUNK3 = "Gao! Gao! Gao!",
		CHESTER = "Gao! Gao! Gao!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Gao! Gao! Gao!",
			WAITING = "Gao! Gao! Gao!",
		},
		COOKEDMANDRAKE = "Gao! Gao! Gao!",
		COOKEDMEAT = "Gao! Gao! Gao!",
		COOKEDMONSTERMEAT = "Gao! Gao! Gao!",
		COOKEDSMALLMEAT = "Gao! Gao! Gao!",
		COOKPOT =
		{
			COOKING_LONG = "Gao! Gao! Gao!",
			COOKING_SHORT = "Gao! Gao! Gao!",
			DONE = "Gao! Gao! Gao!",
			EMPTY = "Gao! Gao! Gao!",
		},
		CORN = "Gao! Gao! Gao!",
		CORN_COOKED = "Gao! Gao! Gao!",
		CORN_SEEDS = "Gao! Gao! Gao!",
		CROW =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		CUTGRASS = "Gao! Gao! Gao!",
		CUTREEDS = "Gao! Gao! Gao!",
		CUTSTONE = "Gao! Gao! Gao!",
		DEADLYFEAST = "Gao! Gao! Gao!",
		DEERCLOPS = "Gao! Gao! Gao!",
		DEERCLOPS_EYEBALL = "Gao! Gao! Gao!",
		DEPLETED_GRASS =
		{
			GENERIC = "Gao! Gao! Gao!",
		},
		DEVTOOL = "Gao! Gao! Gao!",
		DEVTOOL_NODEV = "Gao! Gao! Gao!",
		DIRTPILE = "Gao! Gao! Gao!",
		DIVININGROD =
		{
			COLD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			HOT = "Gao! Gao! Gao!",
			WARM = "Gao! Gao! Gao!",
			WARMER = "Gao! Gao! Gao!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Gao! Gao! Gao!",
			READY = "Gao! Gao! Gao!",
			UNLOCKED = "Gao! Gao! Gao!",
		},
		DIVININGRODSTART = "Gao! Gao! Gao!",
		DRAGONFRUIT = "Gao! Gao! Gao!",
		DRAGONFRUIT_COOKED = "Gao! Gao! Gao!",
		DRAGONFRUIT_SEEDS = "Gao! Gao! Gao!",
		DRAGONPIE = "Gao! Gao! Gao!",
		DRUMSTICK = "Gao! Gao! Gao!",
		DRUMSTICK_COOKED = "Gao! Gao! Gao!",
		DUG_BERRYBUSH = "Gao! Gao! Gao!",
		DUG_GRASS = "Gao! Gao! Gao!",
		DUG_MARSH_BUSH = "Gao! Gao! Gao!",
		DUG_SAPLING = "Gao! Gao! Gao!",
		DURIAN = "Gao! Gao! Gao!",
		DURIAN_COOKED = "Gao! Gao! Gao!",
		DURIAN_SEEDS = "Gao! Gao! Gao!",
		EARMUFFSHAT = "Gao! Gao! Gao!",
		EGGPLANT = "Gao! Gao! Gao!",
		EGGPLANT_COOKED = "Gao! Gao! Gao!",
		EGGPLANT_SEEDS = "Gao! Gao! Gao!",
		DECIDUOUSTREE = 
		{
			BURNING = "Gao! Gao! Gao!",
			BURNT = "Gao! Gao! Gao!",
			CHOPPED = "Gao! Gao! Gao!",
			POISON = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		ACORN = 
		{
		    GENERIC = "Gao! Gao! Gao!",
		    PLANTED = "Gao! Gao! Gao!",
		},
		ACORN_COOKED = "Gao! Gao! Gao!",
		BIRCHNUTDRAKE = "Gao! Gao! Gao!",
		EVERGREEN =
		{
			BURNING = "Gao! Gao! Gao!",
			BURNT = "Gao! Gao! Gao!",
			CHOPPED = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Gao! Gao! Gao!",
			BURNT = "Gao! Gao! Gao!",
			CHOPPED = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		EYEPLANT = "Gao! Gao! Gao!",
		FARMPLOT =
		{
			GENERIC = "Gao! Gao! Gao!",
			GROWING = "Gao! Gao! Gao!",
			NEEDSFERTILIZER = "Gao! Gao! Gao!",
		},
		FEATHERHAT = "Gao! Gao! Gao!",
		FEATHER_CROW = "Gao! Gao! Gao!",
		FEATHER_ROBIN = "Gao! Gao! Gao!",
		FEATHER_ROBIN_WINTER = "Gao! Gao! Gao!",
		FEM_PUPPET = "Gao! Gao! Gao!",
		FIREFLIES =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		FIREHOUND = "Gao! Gao! Gao!",
		FIREPIT =
		{
			EMBERS = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			HIGH = "Gao! Gao! Gao!",
			LOW = "Gao! Gao! Gao!",
			NORMAL = "Gao! Gao! Gao!",
			OUT = "Gao! Gao! Gao!",
		},
		FIRESTAFF = "Gao! Gao! Gao!",

		FISH = "Gao! Gao! Gao!",
		FISHINGROD = "Gao! Gao! Gao!",
		FISHSTICKS = "Gao! Gao! Gao!",
		FISHTACOS = "Gao! Gao! Gao!",
		FISH_COOKED = "Gao! Gao! Gao!",
		FLINT = "Gao! Gao! Gao!",
		FLOWER = "Gao! Gao! Gao!",
		FLOWERHAT = "Gao! Gao! Gao!",
		FLOWER_EVIL = "Gao! Gao! Gao!",
		FOLIAGE = "Gao! Gao! Gao!",
		FOOTBALLHAT = "Gao! Gao! Gao!",
		FROG =
		{
			DEAD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			SLEEPING = "Gao! Gao! Gao!",
		},
		FROGGLEBUNWICH = "Gao! Gao! Gao!",
		FROGLEGS = "Gao! Gao! Gao!",
		FROGLEGS_COOKED = "Gao! Gao! Gao!",
		FRUITMEDLEY = "Gao! Gao! Gao!",
		GEARS = "Gao! Gao! Gao!",
		GHOST = "Gao! Gao! Gao!",
		GOLDENAXE = "Gao! Gao! Gao!",
		GOLDENPICKAXE = "Gao! Gao! Gao!",
		GOLDENPITCHFORK = "Gao! Gao! Gao!",
		GOLDENSHOVEL = "Gao! Gao! Gao!",
		GOLDNUGGET = "Gao! Gao! Gao!",
		GRASS =
		{
			BARREN = "Gao! Gao! Gao!",
			BURNING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		GREEN_CAP = "Gao! Gao! Gao!",
		GREEN_CAP_COOKED = "Gao! Gao! Gao!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Gao! Gao! Gao!",
			INGROUND = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		GUNPOWDER = "Gao! Gao! Gao!",
		HAMBAT = "Gao! Gao! Gao!",
		HAMMER = "Gao! Gao! Gao!",
		HEALINGSALVE = "Gao! Gao! Gao!",
		HEATROCK =
		{
			COLD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			HOT = "Gao! Gao! Gao!",
			WARM = "Gao! Gao! Gao!",
		},
		HOME = "Gao! Gao! Gao!",
		HOMESIGN = "Gao! Gao! Gao!",
		HONEY = "Gao! Gao! Gao!",
		HONEYCOMB = "Gao! Gao! Gao!",
		HONEYHAM = "Gao! Gao! Gao!",
		HONEYNUGGETS = "Gao! Gao! Gao!",
		HORN = "Gao! Gao! Gao!",
		HOUND = "Gao! Gao! Gao!!",
		HOUNDBONE = "Gao! Gao! Gao!",
		HOUNDMOUND = "Gao! Gao! Gao!",
		ICEBOX = "Gao! Gao! Gao!",
		ICEHOUND = "Gao! Gao! Gao!",
		INSANITYROCK =
		{
			ACTIVE = "Gao! Gao! Gao!",
			INACTIVE = "Gao! Gao! Gao!",
		},
		JAMMYPRESERVES = "Gao! Gao! Gao!",
		KABOBS = "Gao! Gao! Gao!",
		KILLERBEE =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		KNIGHT = "Gao! Gao! Gao!",
		KOALEFANT_SUMMER = "Gao! Gao! Gao!",
		KOALEFANT_WINTER = "Gao! Gao! Gao!",
		KRAMPUS = "Gao! Gao! Gao!",
		KRAMPUS_SACK = "Gao! Gao! Gao!",
		LEIF = "Gao! Gao! Gao!",
		LEIF_SPARSE = "Gao! Gao! Gao!",
		LIGHTNING_ROD =
		{
			CHARGED = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		LITTLE_WALRUS = "Gao! Gao! Gao!",
		LIVINGLOG = "Gao! Gao! Gao!",
		LOCKEDWES = "Gao! Gao! Gao!",
		LOG =
		{
			BURNING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		LUREPLANT = "Gao! Gao! Gao!",
		LUREPLANTBULB = "Gao! Gao! Gao!",
		MALE_PUPPET = "Gao! Gao! Gao!",
		MANDRAKE =
		{
			DEAD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		MANDRAKESOUP = "Gao! Gao! Gao!",
		MANDRAKE_COOKED = "Gao! Gao! Gao!",
		MARBLE = "Gao! Gao! Gao!",
		MARBLEPILLAR = "Gao! Gao! Gao!",
		MARBLETREE = "Gao! Gao! Gao!",
		MARSH_BUSH =
		{
			BURNING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		MARSH_PLANT = "Gao! Gao! Gao!",
		MARSH_TREE =
		{
			BURNING = "Gao! Gao! Gao!",
			BURNT = "Gao! Gao! Gao!",
			CHOPPED = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		MAXWELL = "Gao! Gao! Gao!",
		MAXWELLHEAD = "Gao! Gao! Gao!",
		MAXWELLLIGHT = "Gao! Gao! Gao!",
		MAXWELLLOCK = "Gao! Gao! Gao!",
		MAXWELLTHRONE = "Gao! Gao! Gao!",
		MEAT = "Gao! Gao! Gao!",
		MEATBALLS = "Gao! Gao! Gao!",
		MEATRACK =
		{
			DONE = "Gao! Gao! Gao!",
			DRYING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		MEAT_DRIED = "Gao! Gao! Gao!",
		MERM = "Gao! Gao! Gao!!",
		MERMHEAD = "Gao! Gao! Gao!",
		MERMHOUSE = "Gao! Gao! Gao!",
		MINERHAT = "Gao! Gao! Gao!",
		MONKEY = "Gao! Gao! Gao!",
		MONKEYBARREL = "Gao! Gao! Gao!",
		MONSTERLASAGNA = "Gao! Gao! Gao!",
		MONSTERMEAT = "Gao! Gao! Gao!",
		MONSTERMEAT_DRIED = "Gao! Gao! Gao!",
		MOSQUITO =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		MOSQUITOSACK = "Gao! Gao! Gao!",
		MOUND =
		{
			DUG = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		NIGHTLIGHT = "Gao! Gao! Gao!",
		NIGHTMAREFUEL = "Gao! Gao! Gao!",
		NIGHTSWORD = "Gao! Gao! Gao!",
		NITRE = "Gao! Gao! Gao!",
		ONEMANBAND = "Gao! Gao! Gao!",
		PANDORASCHEST = "Gao! Gao! Gao!",
		PANFLUTE = "Gao! Gao! Gao!",
		PAPYRUS = "Gao! Gao! Gao!",
		PENGUIN = "Gao! Gao! Gao!",
		PERD = "Gao! Gao! Gao!",
		PEROGIES = "Gao! Gao! Gao!",
		PETALS = "Gao! Gao! Gao!",
		PETALS_EVIL = "Gao! Gao! Gao!",
		PHLEGM = "Gao! Gao! Gao!.",
		PICKAXE = "Gao! Gao! Gao!",
		PIGGYBACK = "Gao! Gao! Gao!",
		PIGHEAD = "Gao! Gao! Gao!",
		PIGHOUSE =
		{
			FULL = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			LIGHTSOUT = "Gao! Gao! Gao!",
		},
		PIGKING = "Gao! Gao! Gao!",
		PIGMAN =
		{
			DEAD = "Gao! Gao! Gao!",
			FOLLOWER = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			GUARD = "Gao! Gao! Gao!",
			WEREPIG = "Gao! Gao! Gao!",
		},
		PIGSKIN = "Gao! Gao! Gao!",
		PIGTENT = "Gao! Gao! Gao!",
		PIGTORCH = "Gao! Gao! Gao!",
		PINECONE = 
		{
		    GENERIC = "Gao! Gao! Gao!",
		    PLANTED = "Gao! Gao! Gao!",
		},
		PITCHFORK = "Gao! Gao! Gao!",
		PLANTMEAT = "Gao! Gao! Gao!",
		PLANTMEAT_COOKED = "Gao! Gao! Gao!",
		PLANT_NORMAL =
		{
			GENERIC = "Gao! Gao! Gao!",
			GROWING = "Gao! Gao! Gao!",
			READY = "Gao! Gao! Gao!.",
		},
		POMEGRANATE = "Gao! Gao! Gao!",
		POMEGRANATE_COOKED = "Gao! Gao! Gao!",
		POMEGRANATE_SEEDS = "Gao! Gao! Gao!",
		POND = "Gao! Gao! Gao!",
		POOP = "Gao! Gao! Gao!",
		PUMPKIN = "Gao! Gao! Gao!",
		PUMPKINCOOKIE = "Gao! Gao! Gao!",
		PUMPKIN_COOKED = "Gao! Gao! Gao!",
		PUMPKIN_LANTERN = "Gao! Gao! Gao!",
		PUMPKIN_SEEDS = "Gao! Gao! Gao!",
		PURPLEAMULET = "Gao! Gao! Gao!",
		PURPLEGEM = "Gao! Gao! Gao!",
		RABBIT =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		RABBITHOLE = "Gao! Gao! Gao!",
		RAINOMETER = "Gao! Gao! Gao!",
		RATATOUILLE = "Gao! Gao! Gao!",
		RAZOR = "Gao! Gao! Gao!",
		REDGEM = "Gao! Gao! Gao!",
		RED_CAP = "Gao! Gao! Gao!",
		RED_CAP_COOKED = "Gao! Gao! Gao!",
		RED_MUSHROOM =
		{
			GENERIC = "Gao! Gao! Gao!",
			INGROUND = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		REEDS =
		{
			BURNING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
        RELIC = 
        {
            GENERIC = "Gao! Gao! Gao!",
            BROKEN = "Gao! Gao! Gao!",
        },
        RUINS_RUBBLE = "Gao! Gao! Gao!",
        RUBBLE = "Gao! Gao! Gao!",
		RESEARCHLAB = "Gao! Gao! Gao!",
		RESEARCHLAB2 = "Gao! Gao! Gao!",
		RESEARCHLAB3 = "Gao! Gao! Gao!",
		RESEARCHLAB4 = "Gao! Gao! Gao!",
		RESURRECTIONSTATUE = "Gao! Gao! Gao!!",
		RESURRECTIONSTONE = "Gao! Gao! Gao!",
		ROBIN =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Gao! Gao! Gao!",
			HELD = "Gao! Gao! Gao!",
		},
		ROBOT_PUPPET = "Gao! Gao! Gao!",
		ROCK_LIGHT =
		{
			GENERIC = "Gao! Gao! Gao!",
			OUT = "Gao! Gao! Gao!",
			LOW = "Gao! Gao! Gao!",
			NORMAL = "Gao! Gao! Gao!",
		},
		ROCK = "Gao! Gao! Gao!.",
		ROCKS = "Gao! Gao! Gao!",
        ROOK = "Gao! Gao! Gao!",
		ROPE = "Gao! Gao! Gao!",
		ROTTENEGG = "Gao! Gao! Gao!",
		SANITYROCK =
		{
			ACTIVE = "Gao! Gao! Gao!",
			INACTIVE = "Gao! Gao! Gao!",
		},
		SAPLING =
		{
			BURNING = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		SEEDS = "Gao! Gao! Gao!",
		SEEDS_COOKED = "Gao! Gao! Gao!",
		SEWING_KIT = "Gao! Gao! Gao!",
		SHOVEL = "Gao! Gao! Gao!",
		SILK = "Gao! Gao! Gao!",
		SKELETON = "Gao! Gao! Gao!",
		SKULLCHEST = "Gao! Gao! Gao!",
		SMALLBIRD =
		{
			GENERIC = "Gao! Gao! Gao!",
			HUNGRY = "Gao! Gao! Gao!",
			STARVING = "Gao! Gao! Gao!",
		},
		SMALLMEAT = "Gao! Gao! Gao!",
		SMALLMEAT_DRIED = "Gao! Gao! Gao!",
		SPAT = "Gao! Gao! Gao!",
		SPEAR = "Gao! Gao! Gao!",
		SPIDER =
		{
			DEAD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			SLEEPING = "Gao! Gao! Gao!",
		},
		SPIDERDEN = "Gao! Gao! Gao!",
		SPIDEREGGSACK = "Gao! Gao! Gao!",
		SPIDERGLAND = "Gao! Gao! Gao!",
		SPIDERHAT = "Gao! Gao! Gao!",
		SPIDERQUEEN = "Gao! Gao! Gao!",
		SPIDER_WARRIOR =
		{
			DEAD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			SLEEPING = "Gao! Gao! Gao!",
		},
		SPOILED_FOOD = "Gao! Gao! Gao!",
		STATUEHARP = "Gao! Gao! Gao!",
		STATUEMAXWELL = "Gao! Gao! Gao!",
		STEELWOOL = "Gao! Gao! Gao!",
		STINGER = "Gao! Gao! Gao!",
		STRAWHAT = "Gao! Gao! Gao!",
		STUFFEDEGGPLANT = "Gao! Gao! Gao!",
		SUNKBOAT = "Gao! Gao! Gao!",
		SWEATERVEST = "Gao! Gao! Gao!",
		TAFFY = "Gao! Gao! Gao!",
		TALLBIRD = "Gao! Gao! Gao!",
		TALLBIRDEGG = "Gao! Gao! Gao!",
		TALLBIRDEGG_COOKED = "Gao! Gao! Gao!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			HOT = "Gao! Gao! Gao!",
			LONG = "Gao! Gao! Gao!",
			SHORT = "Gao! Gao! Gao!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Gao! Gao! Gao!",
			PICKED = "Gao! Gao! Gao!",
		},
		TEENBIRD =
		{
			GENERIC = "Gao! Gao! Gao!",
			HUNGRY = "Gao! Gao! Gao!",
			STARVING = "Gao! Gao! Gao!",
		},
		TELEBASE =
		{
			VALID = "Gao! Gao! Gao!",
			GEMS = "Gao! Gao! Gao!",
		},
		GEMSOCKET = 
		{
			VALID = "Gao! Gao! Gao!",
			GEMS = "Gao! Gao! Gao!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
			LOCKED = "Gao! Gao! Gao!",
			PARTIAL = "Gao! Gao! Gao!",
		},
		TELEPORTATO_BOX = "Gao! Gao! Gao!",
		TELEPORTATO_CRANK = "Gao! Gao! Gao!",
		TELEPORTATO_POTATO = "Gao! Gao! Gao!",
		TELEPORTATO_RING = "Gao! Gao! Gao!",
		TELESTAFF = "Gao! Gao! Gao!",
		TENT = "Gao! Gao! Gao!",
		TENTACLE = "Gao! Gao! Gao!",
		TENTACLESPIKE = "Gao! Gao! Gao!",
		TENTACLESPOTS = "Gao! Gao! Gao!",
		TENTACLE_PILLAR = "Gao! Gao! Gao!",
		TENTACLE_PILLAR_ARM = "Gao! Gao! Gao!",
		TENTACLE_GARDEN = "Gao! Gao! Gao!",
		TOPHAT = "Gao! Gao! Gao!",
		TORCH = "Gao! Gao! Gao!",
		TRAP = "Gao! Gao! Gao!",
		TRAP_TEETH = "Gao! Gao! Gao!",
		TRAP_TEETH_MAXWELL = "Gao! Gao! Gao!",
		TREASURECHEST = "Gao! Gao! Gao!",
		TREASURECHEST_TRAP = "Gao! Gao! Gao!",
		TREECLUMP = "Gao! Gao! Gao!",
		TRINKET_1 = "Gao! Gao! Gao!",
		TRINKET_10 = "Gao! Gao! Gao!",
		TRINKET_11 = "Gao! Gao! Gao!",
		TRINKET_12 = "Gao! Gao! Gao!",
		TRINKET_13 = "Gao! Gao! Gao!",
		TRINKET_2 = "Gao! Gao! Gao!",
		TRINKET_3 = "Gao! Gao! Gao!",
		TRINKET_4 = "Gao! Gao! Gao!",
		TRINKET_5 = "Gao! Gao! Gao!",
		TRINKET_6 = "Gao! Gao! Gao!",
		TRINKET_7 = "Gao! Gao! Gao!",
		TRINKET_8 = "Gao! Gao! Gao!",
		TRINKET_9 = "Gao! Gao! Gao!",
		TRUNKVEST_SUMMER = "Gao! Gao! Gao!",
		TRUNKVEST_WINTER = "Gao! Gao! Gao!",
		TRUNK_COOKED = "Gao! Gao! Gao!",
		TRUNK_SUMMER = "Gao! Gao! Gao!",
		TRUNK_WINTER = "Gao! Gao! Gao!",
		TURF_CARPETFLOOR = "Gao! Gao! Gao!",
		TURF_CHECKERFLOOR = "Gao! Gao! Gao!",
		TURF_DIRT = "Gao! Gao! Gao!",
		TURF_FOREST = "Gao! Gao! Gao!",
		TURF_GRASS = "Gao! Gao! Gao!",
		TURF_MARSH = "Gao! Gao! Gao!",
		TURF_ROAD = "Gao! Gao! Gao!",
		TURF_ROCKY = "Gao! Gao! Gao!",
		TURF_SAVANNA = "Gao! Gao! Gao!",
		TURF_WOODFLOOR = "Gao! Gao! Gao!",
		TURKEYDINNER = "Gao! Gao! Gao!",
		TWIGS = "Gao! Gao! Gao!",
		UMBRELLA = "Gao! Gao! Gao!",
		UNIMPLEMENTED = "Gao! Gao! Gao!",
		WAFFLES = "Gao! Gao! Gao!",
		WALL_HAY = "Gao! Gao! Gao!",
		WALL_HAY_ITEM = "Gao! Gao! Gao!",
		WALL_STONE = "Gao! Gao! Gao!",
		WALL_STONE_ITEM = "Gao! Gao! Gao!",
		WALL_RUINS = "Gao! Gao! Gao!",
		WALL_RUINS_ITEM = "Gao! Gao! Gao!",
		WALL_WOOD = "Gao! Gao! Gao!",
		WALL_WOOD_ITEM = "Gao! Gao! Gao!",
		WALL_MOONROCK = "Gao! Gao! Gao!",
		WALL_MOONROCK_ITEM = "Gao! Gao! Gao!",
		WALRUS = "Gao! Gao! Gao!",
		WALRUSHAT = "Gao! Gao! Gao!",
		WALRUS_CAMP =
		{
			EMPTY = "Gao! Gao! Gao!",
			GENERIC = "Gao! Gao! Gao!",
		},
		WALRUS_TUSK = "Gao! Gao! Gao!",
		WARG = "Gao! Gao! Gao!",
		WASPHIVE = "Gao! Gao! Gao!",
		WETGOOP = "Gao! Gao! Gao!",
		WINTERHAT = "Gao! Gao! Gao!",
		WINTEROMETER = "Gao! Gao! Gao!",
		WORMHOLE =
		{
			GENERIC = "Gao! Gao! Gao!",
			OPEN = "Gao! Gao! Gao!",
		},
		WORMHOLE_LIMITED = "Gao! Gao! Gao!",
		ACCOMPLISHMENT_SHRINE = "Gao! Gao! Gao!",        
		LIVINGTREE = "Gao! Gao! Gao!",
		ICESTAFF = "Gao! Gao! Gao!",
		REVIVER = "Gao! Gao! Gao!",
		LIFEINJECTOR = "Gao! Gao! Gao!",
		SKELETON_PLAYER =
		{
			MALE = "Gao! Gao! Gao!",
			FEMALE = "Gao! Gao! Gao!",
			ROBOT = "Gao! Gao! Gao!",
		},
		HUMANMEAT = "Gao! Gao! Gao!",
		HUMANMEAT_COOKED = "Gao! Gao! Gao!",
		HUMANMEAT_DRIED = "Gao! Gao! Gao!",
		MOONROCKNUGGET = "Gao! Gao! Gao!",
	},
	DESCRIBE_GENERIC = "Gao! Gao! Gao!",
	DESCRIBE_TOODARK = "Gao! Gao! Gao!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Gao! Gao! Gao!",
	},
}
