-- This information tells other players more about the mod
name = "e01地上洞穴扩展"
description = "把地洞地图搬运到地上，和其他普通地图连在一起"
author = "YY89856191章凡汉化"
version = "2.5.0"

-- This is the URL name of the mod's thread on the forum; the part after the index.php? and before the first & in the URL
-- Example:
-- http://forums.kleientertainment.com/index.php?/files/file/202-sample-mods/
-- becomes
-- /files/file/202-sample-mods/
forumthread = ""

-- This lets other players know if your mod is out of date, update it to match the current version in the game
api_version = 10

--This lets the clients know that they need to download the mod before they can join a server that is using it.
all_clients_require_mod = true

--This let's the game know that this mod doesn't need to be listed in the server's mod listing
client_only_mod = false

--Let the mod system know that this mod is functional with Don't Starve Together
dst_compatible = true

--These tags allow the server running this mod to be found with filters from the server listing screen
server_filter_tags = {"environment","worldgen"}

--Adds an icon to the mod
icon_atlas = "preview.xml"
icon = "preview.tex"

configuration_options =
{
-- Biome Customization

-- Slurper Wilds
	{
		name = "",
		label = "SLURPER WILDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "SlurperWildsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "Tight", data = 0.20},
						{description = "Very Tight", data = 0.25},
					},
		default = 0.15,
	},
	{
		name = "SlurperWildsBlueMushroom",
		label = "Blue Mushrooms",
			hover = "Spawn frequency of Blue Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.08},
						{description = "Less", data = 0.11},
						{description = "Default", data = 0.15},
						{description = "More", data = 0.19},
						{description = "Lots", data = 0.23},
					},
		default = 0.15,
	},
	{
		name = "SlurperWildsLichen",
		label = "Lichen",
			hover = "Spawn frequency of Lichen",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.05},
						{description = "Less", data = 0.15},
						{description = "Default", data = 0.25},
						{description = "More", data = 0.35},
						{description = "Lots", data = 0.45},
					},
		default = 0.25,
	},
	{
		name = "SlurperWildsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.6},
						{description = "Default", data = 1.0},
						{description = "More", data = 1.5},
						{description = "Lots", data = 2.0},
					},
		default = 1.0,
	},
	{
		name = "SlurperWildsSlimyPillar",
		label = "Slimy Pillars",
			hover = "Spawn frequency of Slimy Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.06},
						{description = "Lots", data = 0.07},
					},
		default = 0.05,
	},
	{
		name = "SlurperWildsSlurper",
		label = "Slurpers",
			hover = "Spawn frequency of Slurpers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.15},
						{description = "Less", data = 0.35},
						{description = "Default", data = 0.55},
						{description = "More", data = 0.85},
						{description = "Lots", data = 1.05},
					},
		default = 0.55,
	},
-- Lush Wilds
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "LUSH WILDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "LushWildsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.15},
						{description = "Loose", data = 0.20},
						{description = "Default", data = 0.25},
						{description = "Tight", data = 0.30},
						{description = "Very Tight", data = 0.35},
					},
		default = 0.25,
	},
	{
		name = "LushWildsBlueMushroom",
		label = "Blue Mushrooms",
			hover = "Spawn frequency of Blue Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.08},
						{description = "Less", data = 0.11},
						{description = "Default", data = 0.15},
						{description = "More", data = 0.19},
						{description = "Lots", data = 0.23},
					},
		default = 0.15,
	},
	{
		name = "LushWildsLichen",
		label = "Lichen",
			hover = "Spawn frequency of Lichen",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.05},
						{description = "Less", data = 0.15},
						{description = "Default", data = 0.25},
						{description = "More", data = 0.35},
						{description = "Lots", data = 0.45},
					},
		default = 0.25,
	},
	{
		name = "LushWildsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.6},
						{description = "Default", data = 1.0},
						{description = "More", data = 1.5},
						{description = "Lots", data = 2.0},
					},
		default = 1.0,
	},
	{
		name = "LushWildsSlimyPillar",
		label = "Slimy Pillars",
			hover = "Spawn frequency of Slimy Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.06},
						{description = "Lots", data = 0.07},
					},
		default = 0.05,
	},
	{
		name = "LushWildsDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.002},
						{description = "Less", data = 0.006},
						{description = "Default", data = 0.01},
						{description = "More", data = 0.04},
						{description = "Lots", data = 0.07},
					},
		default = 0.01,
	},
	{
		name = "LushWildsNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.07},
						{description = "More", data = 0.09},
						{description = "Lots", data = 0.11},
					},
		default = 0.07,
	},
	{
		name = "LushWildsCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.06},
						{description = "Default", data = 0.10},
						{description = "More", data = 0.14},
						{description = "Lots", data = 0.18},
					},
		default = 0.10,
	},
-- Light Wilds
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "LIGHT WILDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "LightWildsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "Tight", data = 0.20},
						{description = "Very Tight", data = 0.25},
					},
		default = 0.15,
	},
	{
		name = "LightWildsBlueMushroom",
		label = "Blue Mushrooms",
			hover = "Spawn frequency of Blue Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.07},
						{description = "Default", data = 0.10},
						{description = "More", data = 0.14},
						{description = "Lots", data = 0.18},
					},
		default = 0.10,
	},
	{
		name = "LightWildsLichen",
		label = "Lichen",
			hover = "Spawn frequency of Lichen",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.07},
						{description = "Default", data = 0.10},
						{description = "More", data = 0.14},
						{description = "Lots", data = 0.18},
					},
		default = 0.10,
	},
	{
		name = "LightWildsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.7},
						{description = "More", data = 0.9},
						{description = "Lots", data = 1.1},
					},
		default = 0.7,
	},
	{
		name = "LightWildsSlimyPillar",
		label = "Slimy Pillars",
			hover = "Spawn frequency of Slimy Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.06},
						{description = "Lots", data = 0.07},
					},
		default = 0.05,
	},
	{
		name = "LightWildsCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.7},
						{description = "More", data = 0.9},
						{description = "Lots", data = 1.1},
					},
		default = 0.7,
	},
	{
		name = "LightWildsNightmareLight",
		label = "Nightmare Light",
			hover = "Spawn frequency of Nightmare Light",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.07},
						{description = "More", data = 0.09},
						{description = "Lots", data = 0.11},
					},
		default = 0.07,
	},
-- Rabbit Fields
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "RABBIT FIELDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "RabbitFieldPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.10},
						{description = "Loose", data = 0.15},
						{description = "Default", data = 0.20},
						{description = "Tight", data = 0.25},
						{description = "Very Tight", data = 0.30},
					},
		default = 0.20,
	},
	{
		name = "RabbitFieldCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.8},
					},
		default = 0.4,
	},
	{
		name = "RabbitFieldCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.6},
						{description = "Less", data = 0.8},
						{description = "Default", data = 1.2},
						{description = "More", data = 1.8},
						{description = "Lots", data = 2.6},
					},
		default = 1.2,
	},
	{
		name = "RabbitFieldAllMushrooms",
		label = "All Mushrooms",
			hover = "Spawn frequency of All Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.8},
						{description = "Lots", data = 1.0},
					},
		default = 0.6,
	},
	{
		name = "RabbitFieldRabbitHouse",
		label = "Rabbit Houses",
			hover = "Spawn frequency of Rabbit Houses",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.21},
						{description = "Less", data = 0.41},
						{description = "Default", data = 0.61},
						{description = "More", data = 0.81},
						{description = "Lots", data = 1.01},
					},
		default = 0.61,
	},
	{
		name = "RabbitFieldCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
-- Green Mush
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "GREEN MUSH",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "GreenMushPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.175},
						{description = "Loose", data = 0.225},
						{description = "Default", data = 0.275},
						{description = "Tight", data = 0.325},
						{description = "Very Tight", data = 0.375},
					},
		default = 0.275,
	},
	{
		name = "GreenMushSlurtleMound",
		label = "Slurtle Mounds",
			hover = "Spawn frequency of Slurtle Mounds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "GreenMushDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "GreenMushCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.07},
					},
		default = 0.03,
	},
	{
		name = "GreenMushCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
	{
		name = "GreenMushCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.8},
					},
		default = 0.4,
	},
	{
		name = "GreenMushGreenMushroom",
		label = "Green Mushrooms",
			hover = "Spawn frequency of Green Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.9},
						{description = "More", data = 1.2},
						{description = "Lots", data = 1.5},
					},
		default = 0.9,
	},
	{
		name = "GreenMushSmallMushtree",
		label = "Small Mushtrees",
			hover = "Spawn frequency of Small Mushtrees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
-- Red Mush
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "RED MUSH",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "RedMushPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.175},
						{description = "Loose", data = 0.225},
						{description = "Default", data = 0.275},
						{description = "Tight", data = 0.325},
						{description = "Very Tight", data = 0.375},
					},
		default = 0.275,
	},
	{
		name = "RedMushSlurtleMound",
		label = "Slurtle Mounds",
			hover = "Spawn frequency of Slurtle Mounds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "RedMushDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "RedMushCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.07},
					},
		default = 0.03,
	},
	{
		name = "RedMushCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
	{
		name = "RedMushCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.8},
					},
		default = 0.4,
	},
	{
		name = "RedMushRedMushroom",
		label = "Red Mushrooms",
			hover = "Spawn frequency of Red Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.9},
						{description = "More", data = 1.2},
						{description = "Lots", data = 1.5},
					},
		default = 0.9,
	},
	{
		name = "RedMushMediumMushtree",
		label = "Medium Mushtrees",
			hover = "Spawn frequency of Medium Mushtrees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
-- Blue Mush
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "BLUE MUSH",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "BlueMushPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.175},
						{description = "Loose", data = 0.225},
						{description = "Default", data = 0.275},
						{description = "Tight", data = 0.325},
						{description = "Very Tight", data = 0.375},
					},
		default = 0.275,
	},
	{
		name = "BlueMushSlurtleMound",
		label = "Slurtle Mounds",
			hover = "Spawn frequency of Slurtle Mounds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "BlueMushDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "BlueMushCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.07},
					},
		default = 0.03,
	},
	{
		name = "BlueMushCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
	{
		name = "BlueMushCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.8},
					},
		default = 0.4,
	},
	{
		name = "BlueMushBlueMushroom",
		label = "Blue Mushrooms",
			hover = "Spawn frequency of Blue Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.9},
						{description = "More", data = 1.2},
						{description = "Lots", data = 1.5},
					},
		default = 0.9,
	},
	{
		name = "BlueMushTallMushtree",
		label = "Tall Mushtrees",
			hover = "Spawn frequency of Tall Mushtrees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.7},
						{description = "Lots", data = 0.9},
					},
		default = 0.5,
	},
-- Fungus Plains
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "FUNGUS PLAINS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "FungusPlainsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.10},
						{description = "Loose", data = 0.15},
						{description = "Default", data = 0.20},
						{description = "Tight", data = 0.25},
						{description = "Very Tight", data = 0.30},
					},
		default = 0.20,
	},
	{
		name = "FungusPlainsSlurtleMound",
		label = "Slurtle Mound",
			hover = "Spawn frequency of Slurtle Mound",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.06},
						{description = "Default", data = 0.10},
						{description = "More", data = 0.15},
						{description = "Lots", data = 0.20},
					},
		default = 0.10,
	},
	{
		name = "FungusPlainsDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.06},
						{description = "Default", data = 0.10},
						{description = "More", data = 0.15},
						{description = "Lots", data = 0.20},
					},
		default = 0.10,
	},
	{
		name = "FungusPlainsCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.004},
						{description = "Less", data = 0.007},
						{description = "Default", data = 0.01},
						{description = "More", data = 0.04},
						{description = "Lots", data = 0.07},
					},
		default = 0.01,
	},
	{
		name = "FungusPlainsCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.4},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.8},
						{description = "More", data = 1.2},
						{description = "Lots", data = 1.6},
					},
		default = 0.8,
	},
	{
		name = "FungusPlainsMushTree",
		label = "Mushtrees",
			hover = "Spawn frequency of Mushtrees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.5},
						{description = "More", data = 0.8},
						{description = "Lots", data = 1.1},
					},
		default = 0.5,
	},
	{
		name = "FungusPlainsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.005},
						{description = "Less", data = 0.01},
						{description = "Default", data = 0.02},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.08},
					},
		default = 0.02,
	},
	{
		name = "FungusPlainsGoldNugget",
		label = "Gold Nuggets",
			hover = "Spawn frequency of Gold Nuggets",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
-- Batcave
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "BATCAVE",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "BatCavePrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.10},
						{description = "Loose", data = 0.15},
						{description = "Default", data = 0.20},
						{description = "Tight", data = 0.25},
						{description = "Very Tight", data = 0.30},
					},
		default = 0.20,
	},
	{
		name = "BatCaveTallbirdNest",
		label = "Tallbird Nest",
			hover = "Spawn frequency of Tallbird Nest",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.07},
					},
		default = 0.03,
	},
	{
		name = "BatCaveBats",
		label = "Bats",
			hover = "Spawn frequency of Bats",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.9},
						{description = "Lots", data = 1.2},
					},
		default = 0.6,
	},
	{
		name = "BatCaveGuano",
		label = "Guano",
			hover = "Spawn frequency of Guano",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.07},
						{description = "Less", data = 0.17},
						{description = "Default", data = 0.27},
						{description = "More", data = 0.37},
						{description = "Lots", data = 0.47},
					},
		default = 0.27,
	},
	{
		name = "BatCaveGoldNugget",
		label = "Gold Nuggets",
			hover = "Spawn frequency of Gold Nuggets",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "BatCaveFlint",
		label = "Flint",
			hover = "Spawn frequency of Flint",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
	{
		name = "BatCaveStalagmite",
		label = "Stalagmite",
			hover = "Spawn frequency of Stalagmite",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.8},
					},
		default = 0.4,
	},
	{
		name = "BatCaveCavePillar",
		label = "Cave Pillars",
			hover = "Spawn frequency of Cave Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.08},
						{description = "More", data = 0.11},
						{description = "Lots", data = 0.14},
					},
		default = 0.08,
	},
	{
		name = "BatCaveNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.08},
						{description = "Lots", data = 0.11},
					},
		default = 0.05,
	},
-- Cave Spider Plains
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "CAVE SPIDER PLAINS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "CaveSpiderPlainsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "Tight", data = 0.20},
						{description = "Very Tight", data = 0.25},
					},
		default = 0.15,
	},
	{
		name = "CaveSpiderPlainsSpilagmite",
		label = "Spilagmite",
			hover = "Spawn frequency of Spilagmite",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.025},
						{description = "Less", data = 0.075},
						{description = "Default", data = 0.125},
						{description = "More", data = 0.200},
						{description = "Lots", data = 0.275},
					},
		default = 0.125,
	},
	{
		name = "CaveSpiderPlainsSlurtleMound",
		label = "Slurtle Mounds",
			hover = "Spawn frequency of Slurtle Mounds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.05},
						{description = "Lots", data = 0.07},
					},
		default = 0.03,
	},
	{
		name = "CaveSpiderPlainsCavePillar",
		label = "Cave Pillars",
			hover = "Spawn frequency of Cave Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.08},
						{description = "More", data = 0.11},
						{description = "Lots", data = 0.15},
					},
		default = 0.08,
	},
	{
		name = "CaveSpiderPlainsNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.07},
						{description = "Lots", data = 0.09},
					},
		default = 0.05,
	},
-- Rock Lobster Plains
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "ROCK LOBSTER PLAINS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "RockLobsterPlainsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "Tight", data = 0.20},
						{description = "Very Tight", data = 0.25},
					},
		default = 0.15,
	},
	{
		name = "RockLobsterPlainsRocklobster",
		label = "Rock Lobsters",
			hover = "Spawn frequency of Rock Lobsters",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.05},
						{description = "Less", data = 0.15},
						{description = "Default", data = 0.25},
						{description = "More", data = 0.35},
						{description = "Lots", data = 0.45},
					},
		default = 0.25,
	},
	{
		name = "RockLobsterPlainsGoldNugget",
		label = "Gold Nuggets",
			hover = "Spawn frequency of Gold Nuggets",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.10},
						{description = "Lots", data = 0.15},
					},
		default = 0.05,
	},
	{
		name = "RockLobsterPlainsRocks",
		label = "Rocks",
			hover = "Spawn frequency of Rocks",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.07},
						{description = "Default", data = 0.1},
						{description = "More", data = 0.2},
						{description = "Lots", data = 0.3},
					},
		default = 0.1,
	},
	{
		name = "RockLobsterPlainsFlint",
		label = "Flint",
			hover = "Spawn frequency of Flint",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.03},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.10},
						{description = "Lots", data = 0.15},
					},
		default = 0.05,
	},
	{
		name = "RockLobsterPlainsBoulder",
		label = "Boulders",
			hover = "Spawn frequency of Boulders",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.05},
						{description = "Less", data = 0.1},
						{description = "Default", data = 0.2},
						{description = "More", data = 0.3},
						{description = "Lots", data = 0.4},
					},
		default = 0.2,
	},
	{
		name = "RockLobsterPlainsCavePillar",
		label = "Cave Pillars",
			hover = "Spawn frequency of Cave Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.005},
						{description = "Less", data = 0.01},
						{description = "Default", data = 0.02},
						{description = "More", data = 0.03},
						{description = "Lots", data = 0.04},
					},
		default = 0.02,
	},
	{
		name = "RockLobsterPlainsNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.005},
						{description = "Less", data = 0.01},
						{description = "Default", data = 0.02},
						{description = "More", data = 0.03},
						{description = "Lots", data = 0.04},
					},
		default = 0.02,
	},
-- Monkey Wilds
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "MONKEY WILDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "MonkeyWildsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.07},
						{description = "Default", data = 0.09},
						{description = "Tight", data = 0.11},
						{description = "Very Tight", data = 0.14},
					},
		default = 0.09,
	},
	{
		name = "MonkeyWildsLichen",
		label = "Lichen",
			hover = "Spawn frequency of Lichen",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.2},
						{description = "Default", data = 0.3},
						{description = "More", data = 0.4},
						{description = "Lots", data = 0.5},
					},
		default = 0.3,
	},
	{
		name = "MonkeyWildsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.6},
						{description = "Default", data = 1.0},
						{description = "More", data = 1.8},
						{description = "Lots", data = 2.4},
					},
		default = 1.0,
	},
	{
		name = "MonkeyWildsSlimyPillar",
		label = "Slimy Pillars",
			hover = "Spawn frequency of Slimy Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.05},
						{description = "More", data = 0.07},
						{description = "Lots", data = 0.09},
					},
		default = 0.05,
	},
	{
		name = "MonkeyWildsBananaTree",
		label = "Banana Trees",
			hover = "Spawn frequency of Banana Trees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.07},
						{description = "Default", data = 0.1},
						{description = "More", data = 0.2},
						{description = "Lots", data = 0.3},
					},
		default = 0.1,
	},
	{
		name = "MonkeyWildsSplumonkeyPod",
		label = "Splumonkey Pods",
			hover = "Spawn frequency of Splumonkey Pods",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.04},
						{description = "Default", data = 0.06},
						{description = "More", data = 1.0},
						{description = "Lots", data = 1.4},
					},
		default = 0.06,
	},
	{
		name = "MonkeyWildsSlurper",
		label = "Slurpers",
			hover = "Spawn frequency of Slurpers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.06},
						{description = "Default", data = 0.08},
						{description = "More", data = 1.0},
						{description = "Lots", data = 1.2},
					},
		default = 0.08,
	},
	{
		name = "MonkeyWildsCavePond",
		label = "Cave Ponds",
			hover = "Spawn frequency of Cave Ponds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.03},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.07},
						{description = "More", data = 1.1},
						{description = "Lots", data = 1.5},
					},
		default = 0.07,
	},
	{
		name = "MonkeyWildsNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.04},
						{description = "More", data = 0.07},
						{description = "Lots", data = 1.0},
					},
		default = 0.04,
	},
	{
		name = "MonkeyWildsDepthsWorm",
		label = "Depths Worms",
			hover = "Spawn frequency of Depths Worms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.04},
						{description = "More", data = 0.07},
						{description = "Lots", data = 1.0},
					},
		default = 0.04,
	},
-- Vacant
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "VACANT",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "VacantPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.08},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.12},
						{description = "Tight", data = 0.14},
						{description = "Very Tight", data = 0.16},
					},
		default = 0.12,
	},
	{
		name = "VacantLichen",
		label = "Lichen",
			hover = "Spawn frequency of Lichen",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.4},
						{description = "More", data = 0.5},
						{description = "Lots", data = 0.6},
					},
		default = 0.4,
	},
	{
		name = "VacantCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.8},
						{description = "Lots", data = 1.0},
					},
		default = 0.6,
	},
	{
		name = "VacantSlimyPillar",
		label = "Slimy Pillars",
			hover = "Spawn frequency of Slimy Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.01},
						{description = "Less", data = 0.02},
						{description = "Default", data = 0.03},
						{description = "More", data = 0.04},
						{description = "Lots", data = 0.05},
					},
		default = 0.03,
	},
	{
		name = "VacantSlurper",
		label = "Slurpers",
			hover = "Spawn frequency of Slurpers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.05},
						{description = "Less", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "More", data = 0.25},
						{description = "Lots", data = 0.35},
					},
		default = 0.15,
	},
	{
		name = "VacantSplumonkeyPod",
		label = "Splumonkey Pods",
			hover = "Spawn frequency of Splumonkey Pods",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.14},
						{description = "Default", data = 0.2},
						{description = "More", data = 0.3},
						{description = "Lots", data = 0.4},
					},
		default = 0.2,
	},
	{
		name = "VacantRubble",
		label = "Rubble",
			hover = "Spawn frequency of Rubble",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.04},
						{description = "Less", data = 0.07},
						{description = "Default", data = 0.1},
						{description = "More", data = 0.2},
						{description = "Lots", data = 0.3},
					},
		default = 0.1,
	},
-- Labyrinth
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "LABYRINTH",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "LabyrinthPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.02},
						{description = "Loose", data = 0.03},
						{description = "Default", data = 0.04},
						{description = "Tight", data = 0.05},
						{description = "Very Tight", data = 0.06},
					},
		default = 0.04,
	},
	{
		name = "LabyrinthNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.15},
						{description = "Less", data = 0.30},
						{description = "Default", data = 0.45},
						{description = "More", data = 0.60},
						{description = "Lots", data = 0.75},
					},
		default = 0.45,
	},
	{
		name = "LabyrinthDropperWeb",
		label = "White Spiders",
			hover = "Spawn frequency of White Spiders",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.7},
						{description = "Default", data = 1.0},
						{description = "More", data = 1.4},
						{description = "Lots", data = 1.8},
					},
		default = 1.0,
	},
-- Junkyard Biome
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "JUNKYARD",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "JunkyardBiomePrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.10},
						{description = "Loose", data = 0.15},
						{description = "Default", data = 0.20},
						{description = "Tight", data = 0.25},
						{description = "Very Tight", data = 0.30},
					},
		default = 0.20,
	},
	{
		name = "JunkyardBiomeDropperweb",
		label = "White Spiders",
			hover = "Spawn frequency of White Spiders",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.7},
						{description = "Default", data = 1.2},
						{description = "More", data = 2.0},
						{description = "Lots", data = 2.8},
					},
		default = 1.2,
	},
	{
		name = "JunkyardBiomeNightmarelight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.3},
						{description = "Default", data = 0.5},
						{description = "More", data = 1.0},
						{description = "Lots", data = 1.5},
					},
		default = 0.5,
	},
	{
		name = "JunkyardBiomeRockFlintless",
		label = "Flintless Rocks",
			hover = "Spawn frequency of Flintless Rocks",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.9},
						{description = "More", data = 1.6},
						{description = "Lots", data = 2.2},
					},
		default = 0.9,
	},
	{
		name = "JunkyardBiomeBoulders",
		label = "Boulders",
			hover = "Spawn frequency of Boulders",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.6},
						{description = "Default", data = 0.9},
						{description = "More", data = 1.6},
						{description = "Lots", data = 2.2},
					},
		default = 0.9,
	},
	{
		name = "JunkyardBiomeStalagmite",
		label = "Stalagmite",
			hover = "Spawn frequency of Stalagmite",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.8},
						{description = "Default", data = 1.2},
						{description = "More", data = 1.8},
						{description = "Lots", data = 2.6},
					},
		default = 1.2,
	},
	{
		name = "JunkyardBiomeSpilagmite",
		label = "Spilagmite",
			hover = "Spawn frequency of Spilagmite",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 1.1},
						{description = "Lots", data = 1.8},
					},
		default = 0.6,
	},
	{
		name = "JunkyardBiomeRubble",
		label = "Rubble",
			hover = "Spawn frequency of Rubble",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.3},
						{description = "Less", data = 0.7},
						{description = "Default", data = 1.1},
						{description = "More", data = 1.6},
						{description = "Lots", data = 2.1},
					},
		default = 1.1,
	},
	{
		name = "JunkyardBiomeAncientStatues",
		label = "Ancient Statues",
			hover = "Spawn frequency of Ancient Statues",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.9},
						{description = "Lots", data = 1.4},
					},
		default = 0.6,
	},
	{
		name = "JunkyardBiomeBrokenClockworks",
		label = "Broken Clockworks",
			hover = "Spawn frequency of Broken Clockworks",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.4},
						{description = "Less", data = 0.8},
						{description = "Default", data = 1.2},
						{description = "More", data = 1.7},
						{description = "Lots", data = 2.3},
					},
		default = 1.2,
	},
	{
		name = "JunkyardBiomeTallbirdNest",
		label = "Tallbird Nests",
			hover = "Spawn frequency of Tallbird Nests",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.1},
						{description = "Less", data = 0.2},
						{description = "Default", data = 0.3},
						{description = "More", data = 0.6},
						{description = "Lots", data = 0.9},
					},
		default = 0.3,
	},
	{
		name = "JunkyardBiomeMarbleTree",
		label = "Marble Trees",
			hover = "Spawn frequency of Marble Trees",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.8},
						{description = "More", data = 1.3},
						{description = "Lots", data = 1.9},
					},
		default = 0.8,
	},
	{
		name = "JunkyardBiomeMarblePillar",
		label = "Marble Pillars",
			hover = "Spawn frequency of Marble Pillars",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.8},
						{description = "More", data = 1.3},
						{description = "Lots", data = 1.9},
					},
		default = 0.8,
	},
	{
		name = "JunkyardBiomeNightmareClockworks",
		label = "Nightmare Clockworks",
			hover = "Spawn frequency of Nightmare Clockworks",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.8},
						{description = "More", data = 1.3},
						{description = "Lots", data = 1.9},
					},
		default = 0.8,
	},
	{
		name = "JunkyardBiomeCavePond",
		label = "Cave Ponds",
			hover = "Spawn frequency of Cave Ponds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.7},
						{description = "More", data = 1.2},
						{description = "Lots", data = 1.8},
					},
		default = 0.7,
	},
	{
		name = "JunkyardBiomeMaxwellStatue",
		label = "Maxwell Statue",
			hover = "Spawn frequency of Maxwell Statues",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.5},
						{description = "Default", data = 0.8},
						{description = "More", data = 1.3},
						{description = "Lots", data = 1.9},
					},
		default = 0.8,
	},
	{
		name = "JunkyardBiomeMaxwellsLight",
		label = "Maxwells Light",
			hover = "Spawn frequency of Maxwells Light",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.9},
						{description = "Lots", data = 1.4},
					},
		default = 0.6,
	},
	{
		name = "JunkyardBiomeCaveFlowers",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.4},
						{description = "Less", data = 0.8},
						{description = "Default", data = 1.2},
						{description = "More", data = 0.7},
						{description = "Lots", data = 2.1},
					},
		default = 0,
	},
-- Wild Ponds
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "POND WILDS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "WildPondsPrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.05},
						{description = "Loose", data = 0.10},
						{description = "Default", data = 0.15},
						{description = "Tight", data = 0.20},
						{description = "Very Tight", data = 0.25},
					},
		default = 0.15,
	},
	{
		name = "WildPondsBlueMushroom",
		label = "Blue Mushrooms",
			hover = "Spawn frequency of Blue Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.7},
						{description = "Default", data = 1.2},
						{description = "More", data = 2.0},
						{description = "Lots", data = 2.8},
					},
		default = 1.2,
	},
	{
		name = "WildPondsCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.08},
						{description = "Less", data = 0.14},
						{description = "Default", data = 0.20},
						{description = "More", data = 0.30},
						{description = "Lots", data = 0.40},
					},
		default = 0.20,
	},
	{
		name = "WildPondsSlimyPillar",
		label = "Slimy Pillar",
			hover = "Spawn frequency of Slimy Pillar",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.08},
						{description = "More", data = 0.11},
						{description = "Lots", data = 0.15},
					},
		default = 0.08,
	},
	{
		name = "WildPondsCavePonds",
		label = "Cave Ponds",
			hover = "Spawn frequency of Cave Ponds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.2},
						{description = "Less", data = 0.4},
						{description = "Default", data = 0.6},
						{description = "More", data = 0.8},
						{description = "Lots", data = 1.1},
					},
		default = 0.6,
	},
	{
		name = "WildPondsNightmareLight",
		label = "Nightmare Lights",
			hover = "Spawn frequency of Nightmare Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.02},
						{description = "Less", data = 0.05},
						{description = "Default", data = 0.08},
						{description = "More", data = 0.12},
						{description = "Lots", data = 0.16},
					},
		default = 0.08,
	},
-- Sinkhole
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "SINKHOLE",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "SinkholePrefabDistribution",
		label = "Prefab Distribution",
			hover = "How tightly should the prefabs be placed on the biome",
		options =	{
						{description = "Very Loose", data = 0.20},
						{description = "Loose", data = 0.25},
						{description = "Default", data = 0.30},
						{description = "Tight", data = 0.35},
						{description = "Very Tight", data = 0.40},
					},
		default = 0.30,
	},
	{
		name = "SinkholeCavelight",
		label = "Cave Lights",
			hover = "Spawn frequency of Cave Lights",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 1.1},
						{description = "Less", data = 3.1},
						{description = "Default", data = 5.1},
						{description = "More", data = 8.3},
						{description = "Lots", data = 11.4},
					},
		default = 5.1,
	},
	{
		name = "SinkholeRabbitHouse",
		label = "Rabbit Houses",
			hover = "Spawn frequency of Rabbit Houses",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 2.2},
						{description = "Less", data = 3.4},
						{description = "Default", data = 4.4},
						{description = "More", data = 6.6},
						{description = "Lots", data = 8.8},
					},
		default = 4.4,
	},
	{
		name = "SinkholeFireFlies",
		label = "Fireflies",
			hover = "Spawn frequency of Fireflies",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 7.2},
						{description = "Less", data = 12.4},
						{description = "Default", data = 17.4},
						{description = "More", data = 20.4},
						{description = "Lots", data = 25.2},
					},
		default = 17.4,
	},
	{
		name = "SinkholeReeds",
		label = "Reeds",
			hover = "Spawn frequency of Reeds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 6.2},
						{description = "Less", data = 10.4},
						{description = "Default", data = 14.2},
						{description = "More", data = 18.6},
						{description = "Lots", data = 22.7},
					},
		default = 14.2,
	},
	{
		name = "SinkholeDeciduousTree",
		label = "Deciduous Tree",
			hover = "Spawn frequency of Deciduous Tree",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 2.2},
						{description = "Less", data = 5.4},
						{description = "Default", data = 8.45},
						{description = "More", data = 11.6},
						{description = "Lots", data = 24.7},
					},
		default = 8.45,
	},
	{
		name = "SinkholeBerryBush",
		label = "Berry Bush",
			hover = "Spawn frequency of Berry Bush",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 1.1},
						{description = "Less", data = 2.4},
						{description = "Default", data = 4.5},
						{description = "More", data = 7.6},
						{description = "Lots", data = 10.1},
					},
		default = 4.5,
	},
	{
		name = "SinkholeMushrooms",
		label = "Mushrooms",
			hover = "Spawn frequency of Mushrooms",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 17.2},
						{description = "Less", data = 19.7},
						{description = "Default", data = 21.4},
						{description = "More", data = 23.0},
						{description = "Lots", data = 26.8},
					},
		default = 21.4,
	},
	{
		name = "SinkholeCaveFern",
		label = "Cave Fern",
			hover = "Spawn frequency of Cave Fern",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 12.1},
						{description = "Less", data = 17.4},
						{description = "Default", data = 22.8},
						{description = "More", data = 27.1},
						{description = "Lots", data = 31.8},
					},
		default = 22.8,
	},
	{
		name = "SinkholeCaveFlower",
		label = "Cave Flowers",
			hover = "Spawn frequency of Cave Flowers",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 1.2},
						{description = "Less", data = 2.4},
						{description = "Default", data = 3.8},
						{description = "More", data = 6.8},
						{description = "Lots", data = 9.4},
					},
		default = 3.8,
	},
	{
		name = "SinkholeCarrot",
		label = "Carrots",
			hover = "Spawn frequency of Carrots",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 2.4},
						{description = "Less", data = 5.7},
						{description = "Default", data = 9.6},
						{description = "More", data = 12.7},
						{description = "Lots", data = 16.1},
					},
		default = 9.6,
	},
	{
		name = "SinkholePonds",
		label = "Ponds",
			hover = "Spawn frequency of Ponds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 1.7},
						{description = "Less", data = 3.8},
						{description = "Default", data = 6.8},
						{description = "More", data = 10.4},
						{description = "Lots", data = 15.1},
					},
		default = 6.8,
	},
	{
		name = "SinkholeSlurtleMound",
		label = "Slurtle Mounds",
			hover = "Spawn frequency of Slurtle Mounds",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.7},
						{description = "Less", data = 1.8},
						{description = "Default", data = 2.8},
						{description = "More", data = 4.1},
						{description = "Lots", data = 6.9},
					},
		default = 2.8,
	},
	{
		name = "SinkholeSpiderDen",
		label = "Spider Dens",
			hover = "Spawn frequency of Spider Dens",
		options =	{
						{description = "Disabled", data = 0},
						{description = "Very Few", data = 0.7},
						{description = "Less", data = 1.8},
						{description = "Default", data = 2.8},
						{description = "More", data = 4.1},
						{description = "Lots", data = 6.9},
					},
		default = 2.8,
	},
-- Other Configuration Options
	{
		name = "",
		label = "",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "",
		label = "OTHER OPTIONS",
			hover = "",
		options =	{
						{description = "", data = 0},
					},
		default = 0,
	},
	{
		name = "AncientGuardianHP",
		label = "Ancient Guardian HP",
			hover = "HP of the Ancient Guardian",
		options =	{
						{description = "5000", data = 5000},
						{description = "6000", data = 6000},
						{description = "7000", data = 7000},
						{description = "8000", data = 8000},
						{description = "9000", data = 9000},
						{description = "10000 (Default)", data = 10000},
						{description = "12000", data = 12000},
						{description = "14000", data = 14000},
						{description = "16000", data = 16000},
						{description = "18000", data = 18000},
						{description = "20000", data = 20000},
						{description = "22000", data = 22000},
						{description = "24000", data = 24000},
						{description = "26000", data = 26000},
						{description = "28000", data = 28000},
						{description = "30000", data = 30000},
					},
		default = 10000,
	},
	{
		name = "CaveBiomeWormholes",
		label = "Cave Wormholes",
			hover = "Make Wormholes appear in Cave biomes as well",
		options =	{
						{description = "Enabled", data = 1},
						{description = "Disabled", data = 0},
					},
		default = 1,
	},
}

--Adds a priority to the mod. Loads it before or after other mods. This can help to fix various incompatibilities between other mods.
priority = 8888.18283848586